site_name: Visual Perspective Taking

google_analytics:
  - G-HT2TTGQRXW
  - auto
  
nav:
  - Home: index.md
  - Data: data.md
  - Benchmark: benchmark.md

theme:
  name: "material"
  logo: assets/vpt_icon.png
  favicon: assets/vpt_icon.png
  palette:
    - scheme: default
      primary: dark
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - footnotes
  - extra
  - admonition
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: true
      toc_depth: 1-2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/custom.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js
  - js/custom.js

repo_name: "serre-lab/VPT"
repo_url: "https://github.com/serre-lab/VPT"
